export enum Devices {
  iPhone6 = 'iPhone 6',
  iPhone6Plus = 'iPhone 6 Plus',
  iPhone6s = 'iPhone 6s',
  iPhone6sPlus = 'iPhone 6s Plus',
  iPhoneX = 'iPhone X',
  iPhoneSE1stGen = 'iPhone SE 1st gen',
  iPhone7 = 'iPhone 7',
  iPhone7Plus = 'iPhone 7 Plus',
  iPhone8 = 'iPhone 8',
  iPhone8Plus = 'iPhone 8 Plus',
  iPhoneXS = 'iPhone XS',
  iPhoneXSMax = 'iPhone XS Max',
  iPhoneXR = 'iPhone XR',
  iPhone11 = 'iPhone 11',
  iPhone11Pro = 'iPhone 11 Pro',
  iPhone11ProMax = 'iPhone 11 Pro Max',
  iPhoneSE2ndGen = 'iPhone SE 2nd gen',
  iPhone12Pro = 'iPhone 12 Pro',
  iPhone12ProMax = 'iPhone 12 Pro Max',
  iPhone12Mini = 'iPhone 12 mini',
  iPhone12 = 'iPhone 12',
  iPhone13Pro = 'iPhone 13 Pro',
  iPhone13ProMax = 'iPhone 13 Pro Max',
  iPhone13Mini = 'iPhone 13 mini',
  iPhone13 = 'iPhone 13',
}